"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_UPLOAD_MAX_MEMORY_SIZE = 40 * 1024 * 1024


def _volume_mount_path():
    configured_path = os.getenv('RAILWAY_VOLUME_MOUNT_PATH', '').strip()
    if configured_path:
        return Path(configured_path)
    default_path = Path('/data')
    if default_path.is_dir() and os.access(default_path, os.W_OK):
        return default_path
    return None


VOLUME_MOUNT_PATH = _volume_mount_path()
_configured_data_path = os.getenv('INSTA_KIDS_DATA_PATH', '').strip()
_fallback_data_path = Path('/tmp/instakids-data')
if VOLUME_MOUNT_PATH:
    DATA_STORAGE_PATH = VOLUME_MOUNT_PATH
elif _configured_data_path:
    DATA_STORAGE_PATH = Path(_configured_data_path)
elif _fallback_data_path.is_dir() and os.access(_fallback_data_path, os.W_OK):
    DATA_STORAGE_PATH = _fallback_data_path
else:
    DATA_STORAGE_PATH = BASE_DIR


def _ensure_writable_dir(path):
    """Papka yo'q bo'lsa yaratadi. Yozib bo'lmasa False qaytaradi."""
    try:
        path.mkdir(parents=True, exist_ok=True)
        return os.access(path, os.W_OK)
    except OSError:
        return False


# Ko'rsatilgan papka mavjud bo'lmasa yoki yozib bo'lmasa, SQLite "unable to open database file" bilan qulamasin
if not _ensure_writable_dir(DATA_STORAGE_PATH):
    DATA_STORAGE_PATH = BASE_DIR


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-local-dev-change-me')
if SECRET_KEY == 'django-insecure-local-dev-change-me' and os.getenv('RAILWAY_ENVIRONMENT', '').strip():
    import logging
    logging.getLogger('django').warning(
        "DIQQAT: SECRET_KEY o'rnatilmagan — Railway Variables'da uzun maxfiy SECRET_KEY kiriting!"
    )

# Railway provides these environment variables at runtime.
DEBUG = os.getenv('DEBUG', '0').lower() in {'1', 'true', 'yes', 'on'}

def _csv(name, default=''):
    return [item.strip() for item in os.getenv(name, default).split(',') if item.strip()]

ALLOWED_HOSTS = _csv('ALLOWED_HOSTS', '*')
CSRF_TRUSTED_ORIGINS = _csv('CSRF_TRUSTED_ORIGINS', 'http://localhost:5173,http://127.0.0.1:5173,http://localhost:8000,http://127.0.0.1:8000')
RAILWAY_PUBLIC_DOMAIN = os.getenv('RAILWAY_PUBLIC_DOMAIN', '').strip()
if RAILWAY_PUBLIC_DOMAIN:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RAILWAY_PUBLIC_DOMAIN}')
CORS_ALLOWED_ORIGINS = _csv('CORS_ALLOWED_ORIGINS', 'http://localhost:5173,http://127.0.0.1:5173')
if RAILWAY_PUBLIC_DOMAIN:
    CORS_ALLOWED_ORIGINS.append(f'https://{RAILWAY_PUBLIC_DOMAIN}')
# Frontend servisi manzili (masalan https://instakids.up.railway.app) — CSRF uchun ham ishonchli
FRONTEND_URL = os.getenv('FRONTEND_URL', '').strip().rstrip('/')
if FRONTEND_URL:
    CSRF_TRUSTED_ORIGINS.append(FRONTEND_URL)
    CORS_ALLOWED_ORIGINS.append(FRONTEND_URL)
CORS_ALLOW_CREDENTIALS = True
# Railway proxy orqasida HTTPS to'g'ri aniqlansin
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# Cookie transporti muhitga mos bo'lsin:
# - lokal Vite (http://localhost:5173) -> Secure=False, aks holda Chrome session cookie'ni yubormaydi;
# - Railway/HTTPS -> Secure=True.
# Istasa COOKIE_SECURE=0/1 bilan majburan belgilash mumkin.
_cookie_secure_env = os.getenv('COOKIE_SECURE', '').strip().lower()
if _cookie_secure_env in {'1', 'true', 'yes', 'on'}:
    COOKIE_SECURE = True
elif _cookie_secure_env in {'0', 'false', 'no', 'off'}:
    COOKIE_SECURE = False
else:
    COOKIE_SECURE = bool(
    RAILWAY_PUBLIC_DOMAIN
    or os.getenv('RAILWAY_ENVIRONMENT', '').strip()
    or FRONTEND_URL.startswith('https://')
)

CSRF_COOKIE_SECURE = COOKIE_SECURE
SESSION_COOKIE_SECURE = COOKIE_SECURE
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'plat',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

def _database():
    url = os.getenv('DATABASE_URL', '').strip()
    if url:
        from urllib.parse import urlparse, unquote
        u = urlparse(url)
        return {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': u.path.lstrip('/'),
            'USER': unquote(u.username or ''),
            'PASSWORD': unquote(u.password or ''),
            'HOST': u.hostname,
            'PORT': u.port or 5432,
            'CONN_MAX_AGE': 60,
            'CONN_HEALTH_CHECKS': True,
        }
    path = DATA_STORAGE_PATH / 'db.sqlite3'
    return {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': path,
        'OPTIONS': {
            'timeout': 30,
            'transaction_mode': 'IMMEDIATE',
            # WAL: o'qish yozishni bloklamaydi — ko'p foydalanuvchi bir vaqtda ishlaganda "database is locked" bo'lmaydi
            'init_command': 'PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL; PRAGMA busy_timeout=30000;',
        },
    }


DATABASES = {'default': _database()}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Frontend alohida servisda (frontend/ papka). Backend faqat API + admin + media beradi.

# Google bilan kirish (Google Cloud Console'dagi OAuth Client ID)
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '').strip()


MEDIA_URL = '/media/'
MEDIA_ROOT = DATA_STORAGE_PATH / 'media'

# Ma'lumot deploydan keyin saqlanib qoladimi? (Postgres yoki Volume bo'lsa — ha)
DATA_PERSISTENT = bool(os.getenv('DATABASE_URL', '').strip() or VOLUME_MOUNT_PATH)
if not DATA_PERSISTENT and not DEBUG:
    import logging
    logging.getLogger('django').warning(
        "DIQQAT: DATABASE_URL ham, Railway Volume ham yo'q — ma'lumotlar har deployda O'CHIB KETADI!"
    )

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
