# Generated by Django 6.1.1 on 2026-10-01 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat', '0004_moderationreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='close_time',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='open_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
